### ISSUE TITLE
Embedding nginxpy in nginx.conf ?

### ISSUE THREAD

**Issue by nyue** [decentfox/nginxpy#8]
Is this software meant to embed python in nginx like how lua is embedded in nginx ?

I have yet to find any documentation nor example *.conf file which illustrate this embedding.

The docs [link](https://nginxpy.readthedocs.io/) is broken.

Cheers

**Comment by fantix** [comment]
Yes, we hoped to support [ASGI](https://asgi.readthedocs.io/en/latest/) in NGINX natively, but due to time and resources, this project has been discontinued for a while.
